### ISSUE TITLE
In parlai/agents/kbrd/modules.py #45

### ISSUE THREAD

**Issue by xiaolan98** [THUDM/KBRD#11]
edge_list.append((entity, entity, 185))

Why the self-loop relationship is set to 185?

Besides, there exists a self-loop relationship for movies, stated in  parlai/tasks/redial/build.py #209.
 Will this cause the duplicate self-loop relationship for movies?

**Comment by qibinc** [comment]
Hi @xiaolan98 ,

Thanks for being interested in this work.

Q1: In `data/redial/subkg.pkl`, the self-loop relation is indexed at 185.
Q2: The following guarantees the self-loop relationships are not duplicated

https://github.com/THUDM/KBRD/blob/567852dfc0c28bd6798342858538b103c5e8a7f7/parlai/agents/kbrd/modules.py#L48-L49

**Comment by xiaolan98** [comment]
Thanks for your reply.
It's really helpful

**Comment by xiaolan98** [comment]
Hi @qibinc,
I run the code twice, load the subkg.pkl and find the 'self-loop' index are different ( both not 185). But the results didn't change so much.

**Comment by qibinc** [comment]
Hi @xiaolan98 ,

May I ask how did you find the 'self-loop' index different? I got 185 every time running the code. 

Thanks!

**Comment by xiaolan98** [comment]
Yes, the self-loop is different. Maybe my change causes this problem. Never Mind, It doesn't matter.
