### ISSUE TITLE
对话和建议的融合

### ISSUE THREAD

**Issue by chrislouis0106** [THUDM/KBRD#14]
您好，我有些问题想请教您。如果您可以抽出宝贵时间解答，我将不胜感激。
Q1：diversity_score.py文件中input的命令行参数代表什么呢，我对这个py文件如何实现多样式的评分不是很了解
Q2：我在parlai/agents/kbrd/kbrd.py下的eval_step函数的最后一行添加了“return Output(list(map(str, return_dict["scores"].argmax(dim=1).tolist())))”，但是对对话模型做测试任然是unk的标识符，请问这是因为什么呢
Q3：我在运行display_model.py是，对kbrd模型测试，可以看到turn = 1,4,6等，对dialogue模型测试，并没有明显的轮次信息，同时也可以明显看到建议系统也是对话形式，同时给出建议的候选项和选项；此外建议系统是用的对话的实体链接和知识图谱中抽取的实体提升建议性能，所以我不太明白这里的turn可以跳数和对话系统关系，以及为什么建议系统是一种对话形式呢
Q4：关于show_bias.py，之前的提问和您的回复都没有涉及函数内部，所以再次在这儿请教您。我可以看到执行的结果：给定某个电影，可以看到这个电影的偏向的前100个词汇，但是py文件中的几行代码使我并不能理解数据流动的过程，如下图
![image](https://user-images.githubusercontent.com/31423097/80311854-afe58700-8814-11ea-98d3-dc045f7bd7ec.png)
我的问题有点儿多啦，如果您可以在百忙之中回去，我将万分感谢
祝：一切顺利

**Comment by qibinc** [comment]
Hi @Ashappyboy ,

1. 这个脚本的 input argument 是一个text文件。这个文件的每一行代表模型生成/ground truth的一个 sample，它会逐行读取，并且计算所有的 n-gram 以及 unique 的 n-gram 数目。不过 parlai 生成的结果有许多不需要的信息需要过滤掉。比如，我们可以先讲结果存下来`python display_model xxx ...  > output.txt`。然后提取其中需要的，如果是要模型生成的结果，那就 cat output.txt | grep "TorchAgent" > output_filtered.txt，如果需要 ground truth，就用 cat output.txt | grep "eval_labels_choice" > output_filtered.txt。得到文件的每一行都以 [XXX] 开头，因此在 diversity_scorer.py 的第 32 行有[1:]。
2. `kbrd.py` 的 `eval_step` 不会在对话模型中调用到。因为 paper 中我们分离了 dialog 和 recommender 的 evaluation。这是因为如果对话中生成出 recommended item 转成文本，在计算 bleu score 时候会影响结果，而我们认为衡量对话内容的质量不应该受到推荐出的电影名字的影响，因此这里都是 unk；
3. 因为此 setting 下推荐系统需要用到之前的对话上下文中出现的 item，所以输出的对话形式实际上是提供这一上下文。区别于传统的推荐系统，是由用户的历史点击 item 作为上下文；
4. 首先，`agent.model.kbrd` 是我们的推荐模型，在给出 movie entities 之后，它输出 paper 式 (5) 中的 user representation ，也就是这里的 `up`。然后根据3.2中的式 (8)，即一个两层的 fully connected，就得到 `up_bias`，最后就是在整个 vocabulary 中取 topk了。`idxs > 100`是因为，我们的 vocabulary 编号是根据整个 corpus 中的词频，也就是说 "a", "the" 之类高频却无意义的词，对应于 paper 中说的停止词过滤。

Best,
Qibin

**Comment by chrislouis0106** [comment]
谢谢您的耐心回复和指导，虽然现在模型搭建的地方还有些细节不懂，我接下来也会继续跟踪您的工作。
不知道是否方便加一下您的微信吗？
谢谢您
祝福您一切顺利！

**Comment by qibinc** [comment]
Hi @Ashappyboy ,

没问题，我的微信号是 chenqibin99.

Best,
Qibin
