### ISSUE TITLE
Understanding generated Dialogues

### ISSUE THREAD

**Issue by ahtsham58** [THUDM/KBRD#15]
Hi, 

I trained the system successfully this is what i get as output.
![image](https://user-images.githubusercontent.com/23135687/80511756-d1618280-897c-11ea-8fef-0bb9b32a79be.png)

i tried to use your given line of code to get movie ids in the sentences but it did not work for me. I added a line `return Output(list(map(str, return_dict["scores"].argmax(dim=1).tolist())))` at the end of eval_step in this file https://github.com/THUDM/KBRD/blob/master/parlai/agents/kbrd/kbrd.py and then run python scripts/display_model.py -t redial -mf saved/both_rgcn_0 -dt test.
![image](https://user-images.githubusercontent.com/23135687/80512140-5a78b980-897d-11ea-8b06-683f7dadc7a8.png)

My goal is to get movie ids within dialogue sentences. please guide ..
Secondly, I want to understand the dialogue flow. Like what is candidate label, eval lable etc. 

looking forward to your positive response

**Comment by qibinc** [comment]
**Edit: maintaining for future reference of the same question:** 

```
1. Dialog flow format.
The ParlAI lib is quite rigorous on the output format so we actually hacked a bit to display the information we want to see.

[redial]: dialog history
[label_candidates]: turn | mentioned movies | target movies | mentioned entities | ground truth response
[eval_labels]: ground truth response
[KbrdAgent]: predicted movie id to fit in the ground truth response.

2. Dialog contents & movie ids
Note that the both_rgcn_0 model is just the recommender part so the prediction [KbrdAgent] here is just the movieId. You can lookup the corresponding movie by movieId in `data/redial/entity2entityID.pkl`. 

To see the generated dialog sentences you need to run display_model on the transformer model (after running bash scripts/t2t_rec_rgcn.sh). 
```
