### ISSUE TITLE
通过什么命令生成测试时的回复

### ISSUE THREAD

**Issue by lightcome** [THUDM/KBRD#16]
感谢您优秀的工作，但是没有看到如何生成测试时回复的命令，请问如果想看测试时生成的回复应该执行什么命令

**Comment by yooli23** [comment]
感谢作者的工作！我也有同样的问题，看了您之前的issue里的回答似乎应该执行display_model.py应该可以看到，但我运行后只看到了ground truth，能否请您再次解答下，谢谢！

**Comment by qibinc** [comment]
Hi @lightcome @yooli23 ,

抱歉这么久才给你答复，由于我们分开测试了dialog 和 recommender，目前的 repo 里生成回复需要分为两个部分：

#### 生成对话
`python scripts/display_model.py -t redial -mf saved/transformer_rec_both_rgcn_0 -dt test`

其中 [TorchAgent] 行是我们的模型生成的文本。

#### 生成推荐
请在 https://github.com/THUDM/KBRD/blob/master/parlai/agents/kbrd/kbrd.py 的 `eval_step` 函数最后加上 `return Output(list(map(lambda x: str(self.movie_ids[x]), outputs.argmax(dim=1).tolist())))`，并运行

`python scripts/display_model.py -t redial -mf saved/both_rgcn_0 -dt test`

其中 [KbrdAgent] 行是我们的模型推荐的 item 的 entity id，可以在 `data/redial/entity2entityID.pkl` 里查找到对应的电影名。

尽管这些操作不影响对论文结果的复现，我最近会把这些操作整合起来可以方便地生成可读的回复，感谢您的耐心。

**Comment by yooli23** [comment]
非常感谢你的回复！我尝试运行了：
`python scripts/display_model.py -t redial -mf saved/transformer_rec_both_rgcn_0 -dt test`

但我有两个问题不太清楚：
1. 有一些例子里[eval_labels]下面似乎没有[TorchAgent], 只有一些横线，如下图。请问这些例子是什么意思？
![image](https://user-images.githubusercontent.com/64682660/88223967-30056800-cc1d-11ea-99a4-498c3dfdb4a8.png)

2. 请问[redial] 下面是每一行是一个worker说的话吗？因为有些对话似乎不太对，如下图，第四行的"have you ever seen __unk__ ?"不太像是seeker说的话
![image](https://user-images.githubusercontent.com/64682660/88225596-9be8d000-cc1f-11ea-9ac9-129127c46e19.png)

非常感谢你优秀的工作和耐心得回答，谢谢！

**Comment by qibinc** [comment]
Hi @yooli23 ,

[redial] 是当前句之前的对话历史，包含两方说的话。横线代表对话末尾，此时 model 可能选择结束并不输出任何东西。因为我们用了 ParlAI 框架，输出格式方面可以参考 ParlAI 的文档。

**Comment by yooli23** [comment]
@qibinc 明白了，感谢您积极的回复，很棒的work，谢谢！

**Comment by qibinc** [comment]
Hi 我更新了生成回复的代码，现在可以看到具体推荐的电影了，具体用法还是没变，请看readme中response generation的部分，感谢！
