### ISSUE TITLE
Distinct-N的计算方式

### ISSUE THREAD

**Issue by lisk123** [THUDM/KBRD#17]
Hi，您好！首先感谢您开源代码！在运行了您的开源代码后，我对Distinct-N的计算方式有些不解。
运行您的代码后，Recall@1，PPL这些指标都能复现，但Distinct-N这个指标，和论文汇报的差距较大。
因此想请教您Distinct-N的具体计算方式。
以N=2为例，我理解的Distinct-N的计算方式是：在生成的所有答句中（即test上的所有句子），不同的2-grams占总共的2-grams的比例。这样算出来Distinct的值远低于您论文中的结果。Distinct-3=0.090 (5019 / 55638)，Distinct-4=0.14 (7006 / 49288)。
因此想请教您Distinct-N的计算方式，以及自己究竟那里做错了。

另附上一些generation的句子，每行是一个句子。不知我是否正确复现了您的生成模型：

#########################################
hello !
"Moana  (2016)" is a good one
she was she she she was in "Moana  (2016)" she was in it she was she she she she did she liked "Frozen (2013)"
she 's in it . she 's a new year old old , but she 's a great actress .
bye
hello ! what kind of movies are you looking for ?
have you seen "Shutter Island  (2010)" ?
"Shutter Island  (2010)" is another one that i liked .
it 's a great movie !
you 're welcome ! have a great day !
hello , what kind of movies do you like ?
i 'm good . what kind of movies do you like ?
i have n't seen that one . i will check it out .
i have n't seen it , but i have heard of it .
hello ! what kind of movies are you looking for ?
i like drama . have you seen "Jumanji  (2017)" ?
i have n't seen that one . i have n't seen it . i have n't seen "The Help  (2011)" . i have seen it .
i have n't seen that one . i have n't seen it . i have n't seen "Black Panther (2018)" . i have n't seen it .
i have n't seen that one . i will check it out !
i have n't seen that one !
################################################

可以看出"i have n't seen that one ."这种固定搭配还是经常出现在答句中的。

期待您的解答，感谢您！

**Comment by lisk123** [comment]
感谢作者的邮件解答，问题已经解决了！

**Comment by cyente** [comment]
同样在出现了这个问题，不知道是如何解决的？

**Comment by aianshay** [comment]
Hi, how did you calculate the dist metric? which code did you use? Thanks a lot
