### ISSUE TITLE
关于training时指定的参数

### ISSUE THREAD

**Issue by tanyue2019** [THUDM/KBRD#18]
您好，真的非常感谢您的开源代码给了我学习的机会
我想请问一下在training时，num_exps指定为何值可以取得比较好的结果呢？
非常期待您的回答，谢谢

**Comment by qibinc** [comment]
您好，num_exps 用来指定重复实验的次数，以估计单次实验的随机误差，不影响主要的结果。在 gpu 资源较少的情况下可以设置为 1

**Comment by tanyue2019** [comment]
好的，非常感谢~
