### ISSUE TITLE
关于如何应用

### ISSUE THREAD

**Issue by tanyue2019** [THUDM/KBRD#19]
您好，您现在的测试是运行display_model，请问是否有可能实现自定义对话呢？比如通过命令行与系统进行对话推荐

**Comment by tanyue2019** [comment]
您好，您能给出一点对于“将该模型应用在命令行自定义聊天”宝贵的建议吗？谢谢！

**Comment by tanyue2019** [comment]
您好，现在我正在研究interactive.py的代码，我注意到您提起过 只能用数据集中特定的数据进行测试，我想麻烦问您一下如果是用Redial测试集里的语言 是否有可能通过interactive与模型对话呢？

**Comment by qibinc** [comment]
Hi @tanyue2019 ,

抱歉，这个仓库的代码无法实现 interactive 对话，并且我们不建议这么做。主要原因是 entity linking 部分是对训练集预处理好的，如果用户输入新的句子就没法运行 entity linking 以及之后和 entity/kg 相关的模型。需要自己配置 dbpedia，这部分可以参考 https://github.com/THUDM/KBRD/blob/master/parlai/tasks/redial/extract_entities.py。

**Comment by qibinc** [comment]
可以参考这个最新工作的代码 https://github.com/Lancelot39/KGSF，可能更容易修改

**Comment by tanyue2019** [comment]
谢谢！那请问如果只用redial测试集里面的语句  有可能实现命令行对话吗？

**Comment by qibinc** [comment]
@tanyue2019 

不确定你说的“命令行对话”是指什么。如果是用redial测试集的语句，就不是 interactive 的，用 display_model.py 就可以实现。如果需要 interactive (用户键入)，就存在上面提到的问题。

**Comment by tanyue2019** [comment]
谢谢您！ 如果用户interactive键入测试集里面的语句，可以吗？

**Comment by qibinc** [comment]
如果不让用户自由输入，而是 retrieve 一个测试集里存在过的句子，这样相对更加方便一些，不需要用到 dbpedia docker。

**Comment by qibinc** [comment]
可以参考 `text_dict.pkl` 文件里的信息

**Comment by tanyue2019** [comment]
嗯嗯，限定用户只能输入测试集里存在的语句，这个可以通过修改现在仓库中的interactive.py实现吧？

**Comment by qibinc** [comment]
不确定修改 `interactive.py` 是否足以实现。可能还需要参考一部分 https://github.com/THUDM/KBRD/blob/master/parlai/tasks/redial/agents.py 这里的代码

**Comment by tanyue2019** [comment]
好的，太感谢您了!我也参考了parlAI的网站，现在觉得可能需要向local human agent提供一个 candidates file，从而让local human agent在交互时能够向您的TorchAgent提供正确的label-candidates，现在还不知道我的想法是否正确，真的谢谢您！

**Comment by tanyue2019** [comment]
关于您上面提到的KGSF，请问您是使用作者要求的pytorch==1.3.0,torch_geometric==1.3.2进行训练的吗？ 现在这两个版本已经没有了，我不太知道如何能够配好正确的环境
