### ISSUE TITLE
Ask for a more detailed instruction on your code.

### ISSUE THREAD

**Issue by luyulalala** [THUDM/KBRD#2]
Hello, I am a freshman in this field and I have read your paper. I really hold great interest in your system thus I  want to try your code but it seems tooooooooo complicated for me. 
So I really hope you can update your Readme When you are free and  give us a more detailed instruction or explanation on your code. It would be a great thing to use your code as our baseline and thanks for your great contribution again!!!!! And it is ok if you are too busy to write Readme.

**Comment by qibinc** [comment]
Hi @luyulalala ,

Thanks for being interested in this work! I'll update the README when I'm free. Our code is based on the [ParlAI](https://github.com/facebookresearch/ParlAI/) framework. And that framework has some proper documentation. For now, you can check out that and run some other baselines with it.

Hope this helps!

**Comment by luyulalala** [comment]
Thanks a lot!! I believe it would be helpful and I have sent an e-mail to give a specific probelm. Thanks !!!
