### ISSUE TITLE
关于switching network

### ISSUE THREAD

**Issue by tanyue2019** [THUDM/KBRD#20]
您好，抱歉再次打扰您了
我想请问一下如下理解是否正确？
在switching network上，您与REDIAL工作使用了相同的方法（pointer softmax），从而在生成的语句中包含推荐结果，但是在评估时是两个任务分开进行评估。

非常期待您的回复，谢谢！

**Comment by qibinc** [comment]
Hi @tanyue2019 ,

虽然可以生成包含推荐结果的语句，但由于现有的评估方法（除了人工评估）只能分开评估推荐和对话质量，所以我们是这么做的，您的理解没有问题。
