### ISSUE TITLE
Having trouble downloading additional files

### ISSUE THREAD

**Issue by kondilidisn** [THUDM/KBRD#6]
Dear authors, thank you for your contribution.

I am having trouble downloading the 2 files mentioned in the Dataset section of your README. Download starts with very limited speed and then fails. Thank you for your time.

**Comment by qibinc** [comment]
Hi @kondilidisn ,

I've uploaded the same files to Google Drive and updated the README. Please check it out.

**Comment by kondilidisn** [comment]
The Google Drive links work. Downloads completed successfully. Thank you very much for your immediate response!
