### ISSUE TITLE
issues in show_bias.py 

### ISSUE THREAD

**Issue by luyulalala** [THUDM/KBRD#7]
![image](https://user-images.githubusercontent.com/26454989/66899953-785c7d80-f02e-11e9-995e-ce5a253b9f18.png)
Hello Chen, thanks for your updated code first and here is still an issue when I try to run show_bias.py  and I think it maybe a mistake of upper and lower case but I can't find where can I modify.. 
And another question is have you write any interface to check the generated recommender conversation?

Thanks a lot for your contribution

**Comment by qibinc** [comment]
Hi @luyulalala ,

I noticed that you were pointing to model file `saved/both_rgcn_1`, which is the recommender part of the model. However, to get the vocabulary bias, we need to train the dialog part. `bash scripts/t2t_rec_rgcn.sh <num_exps> <gpu_id>` (see README). After training this, we can run `python scripts/show_bias.py -mf saved/transformer_rec_both_rgcn_1` and it should be ok.

For checking generated results, I just uploaded a `display_model.py` in `scripts/`. After training the dialog part, you can run `python scripts/display_model.py -t redial -mf saved/transformer_rec_both_rgcn_1 -dt test`

**Comment by luyulalala** [comment]
Thanks ! it works! I really appreciate what you guys do and help.  Thanks a lot!!!
