### ISSUE TITLE
KeyError: 'recall@50'

### ISSUE THREAD

**Issue by ZhouWlnd** [THUDM/KBRD#8]
When I ran `bash scripts/t2t_rec_rgcn.sh <num_exps> <gpu_id>`, it seemed that everything was OK at first. But after running for a while, I suddenly got this error: 
```
Traceback (most recent call last):
File "parlai/tasks/redial/train_transformer_rec.py", line 36, in <module>
  TrainLoop(opt).train()
File "/data1/tc/KBRD/parlai/scripts/train_model.py", line 581, in train
  value=-t_report['recall@50']
KeyError:  'recall@50' 
```
I look forward to your help, thank you very much.

PS: When I trained the recommender part, everything was OK.

**Comment by qibinc** [comment]
Hi @ZhouWlnd ,

Sorry for the late reply!

Thanks for being interested in this work! This part of the code was added for development. I've already removed it in the latest commit. Please check it out.

Best,
Qibin
